pagopa/pagopa-ecommerce-transactions-service

- .devops/code-review-pipelines.yml
- README.md
- api-spec/payment-requests-api.yaml
- nodo-wsdl/nodoPerPsp.wsdl
- pom.xml
- src/main/java/it/pagopa/transactions/configurations/NodoConfig.java
- src/main/java/it/pagopa/transactions/configurations/WebClientsConfig.java
- src/main/java/it/pagopa/transactions/controllers/PaymentRequestsController.java
- src/main/java/it/pagopa/transactions/exceptions/NodoErrorException.java
- src/main/java/it/pagopa/transactions/repositories/PaymentRequestInfo.java
- src/main/java/it/pagopa/transactions/repositories/PaymentRequestsInfoRepository.java
- src/main/java/it/pagopa/transactions/services/PaymentRequestsService.java
- src/main/java/it/pagopa/transactions/utils/soap/JaxbContextContainer.java
- src/main/resources/application.properties
- src/test/java/it/pagopa/transactions/configurations/NodoConfigTest.java
- src/test/java/it/pagopa/transactions/controllers/PaymentRequestsControllerTest.java
- src/test/java/it/pagopa/transactions/services/PaymentRequestsServiceTest.java
- src/test/java/it/pagopa/transactions/services/TransactionServiceTests.java
- src/test/java/it/pagopa/transactions/util/Jaxb2SoapEncoderTest.java
- src/test/java/it/pagopa/transactions/utils/soap/Jaxb2SoapEncoderTest.java
- add new nodoPerPsp.wsdl to generate client fo _nodoVerificaRPT_;
- update nodo client configuration to generate client according to `nodeForPsp.wsdl` and `nodoPerPsp.wsdl`;
- retrive paymentRequestInfo with _nodoVerificaRPT_ or _verifyPaymentNotice_ according to payment model (NM3);
- redis cache for paymentRequestInfo with TTL 10 min;
The goal of this PR is to create a new API to retrive the information related to payment request, using the _nodoVerificaRPT_ or _verifyPaymentNotice_  and a cache with payment request info and isNM3 flag. For more details https://pagopa.atlassian.net/wiki/spaces/I/pages/492339720/eCommerce+pagoPA+Design+Review#RF-1.-Come-client-di-eCommerce-voglio-poter-recuperare-le-informazione-di-un-avviso-pagoPA;
unit test & …
> [CHK-584] Get payment request info given notice code and tax code

- src/main/java/it/pagopa/transactions/client/NodoPerPspClient.java
- src/main/java/it/pagopa/transactions/configurations/NodoConfig.java
- src/main/java/it/pagopa/transactions/services/PaymentRequestsService.java
- src/main/java/it/pagopa/transactions/utils/NodoOperations.java
- src/test/java/it/pagopa/transactions/configurations/NodoConfigTest.java
- src/test/java/it/pagopa/transactions/services/PaymentRequestsServiceTest.java
- src/test/java/it/pagopa/transactions/utils/NodoOperationsTest.java
Removed Nodo base requests build as DI beans and class attribute
This fix is needed since having base request as clients classes attribute cause side-effect when multiple concurrent requests override requests values with the latest processed ones
Local test elaborating 5 payment notice concurrent processing requests
> [CHK-894] fix: nodo request building side-effect

- api-spec/transactions-api.yaml
- src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandler.java
- src/main/java/it/pagopa/transactions/controllers/TransactionsController.java
- src/test/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizizationHandlerTest.java
- src/test/java/it/pagopa/transactions/controllers/TransactionsControllerTest.java
Since for some payment methods the pgs is clear and is not valued by apim policy it has been set as not mandatory in the  requestTransactionAuthorization post definition in the yaml file. 
- pgsId not mandatory in yaml file
- transaction controller update
> [CHK-916] (branch CKH-911) x pgs id not mandatory

- src/main/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandler.java
- src/test/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandlerTest.java
Add logic for send TransactionClosedEvent on the closure event queue in case the transactions was previously authorized and Nodo closePayment response outcome is KO or the HTTP response status code is an unrecoverable ones (such as 400).
This event is sent with visibility timeout set to 0 so that events dispatcher can process it as soon as possible and perform transaction rollback logic.
This newly written event will be read by ecommerce event-dispatcher in order to perform transaction refund.
Local junit tests + local test using ecommerce local mocking PGS and Nodo responses
> feat: add TransactionClosedEvent send on queue

- api-spec/transactions-api.yaml
- pom.xml
- src/main/java/it/pagopa/transactions/exceptions/InvalidRequestException.java
- src/main/java/it/pagopa/transactions/services/TransactionsService.java
- src/test/java/it/pagopa/transactions/documents/TransactionDocumentTest.java
- src/test/java/it/pagopa/transactions/projections/handlers/AuthorizationUpdateProjectionHandlerTest.java
- src/test/java/it/pagopa/transactions/services/TransactionServiceTest.java
- src/test/java/it/pagopa/transactions/services/TransactionServiceTests.java
Unknown clientId enum is not acceptable
All reference to ClientId.UNKNOWN enum
Enforce security and expose only to well known client
To be merged AFTER https://github.com/pagopa/pagopa-ecommerce-commons/pull/20
> [CHK-962] clientId unknown removal

- src/main/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandler.java
- src/test/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandlerTest.java
Invalidate cache after closePaymentV2 with outcome OK or KO or generic error
After invoking the node to execute closePaymentV2, in case of OK, KO outcome or generic error we need to invalidate the cache for the rptId handled by the transaction. This is to delegate to the node the management of a possible further attempt of the user.
The tests were performed with pagopa-ecommerce-local
> CHK-1127-invalidate-cache-after-closePyament

- api-spec/transactions-api.yaml
- api-tests/pagoPA-eCommerce.postman_collection.json
- helm/Chart.yaml
- pom.xml
- src/main/java/it/pagopa/transactions/commands/handlers/TransactionActivateHandler.java
- src/main/java/it/pagopa/transactions/projections/handlers/AuthorizationUpdateProjectionHandler.java
- src/main/java/it/pagopa/transactions/projections/handlers/TransactionsActivationProjectionHandler.java
- src/main/java/it/pagopa/transactions/services/TransactionsService.java
- src/main/java/it/pagopa/transactions/utils/NodoOperations.java
- src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
- src/test/java/it/pagopa/transactions/commands/handlers/TransactionInitializerHandlerTest.java
- src/test/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizizationHandlerTest.java
- src/test/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandlerTest.java
- src/test/java/it/pagopa/transactions/commands/handlers/TransactionUpdateAuthorizationHandlerTest.java
- src/test/java/it/pagopa/transactions/commands/handlers/TransactionsActivationProjectionHandlerTest.java
- src/test/java/it/pagopa/transactions/documents/TransactionDocumentTest.java
- src/test/java/it/pagopa/transactions/projections/handlers/AuthorizationUpdateProjectionHandlerTest.java
- src/test/java/it/pagopa/transactions/projections/handlers/CancellationRequestProjectionHandlerTests.java
- src/test/java/it/pagopa/transactions/projections/handlers/ClosureErrorProjectionHandlerTest.java
- src/test/java/it/pagopa/transactions/projections/handlers/ClosureSendProjectionHandlerTests.java
- src/test/java/it/pagopa/transactions/projections/handlers/TransactionUserReceiptProjectionHandlerTest.java
- src/test/java/it/pagopa/transactions/services/TransactionServiceTest.java
- src/test/java/it/pagopa/transactions/services/TransactionServiceTests.java
- src/test/java/it/pagopa/transactions/utils/NodoOperationsTest.java
Pass id cart to activate and save it in transaction view and event store
Added new field `idcart` in newTransaction request body
Save it in transaction document and transaction activated event
Pass it to the activate nodo call in the payment note field
Updated junit test
Added postman test
This field is required to track idcart passed from creditor institution when post carts is invoked
Test were performed locally
> [CHK-1399] pass idcart in activateV2

- src/main/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandler.java
- src/test/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandlerTest.java
Fix ClosePaymentRequest additionalInformations.timestampOperation date format to be formatted in `yyyy-MM-ddThh:mm:ss` format
Those modifications are needed to format `timestampOperation` closePayment field correctly
Junit tests
> fix: additionalPaymentInformations.timestampOperation format

- api-spec/transactions-api.yaml
- pom.xml
- src/main/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandler.java
- src/main/java/it/pagopa/transactions/commands/handlers/TransactionUpdateAuthorizationHandler.java
- src/main/java/it/pagopa/transactions/projections/handlers/AuthorizationUpdateProjectionHandler.java
- src/main/java/it/pagopa/transactions/utils/AuthRequestDataUtils.java
- src/main/java/it/pagopa/transactions/utils/TransactionsUtils.java
- src/test/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandlerTest.java
- src/test/java/it/pagopa/transactions/commands/handlers/TransactionUpdateAuthorizationHandlerTest.java
- src/test/java/it/pagopa/transactions/controllers/TransactionsControllerTest.java
- src/test/java/it/pagopa/transactions/documents/TransactionDocumentTest.java
- src/test/java/it/pagopa/transactions/projections/handlers/AuthorizationUpdateProjectionHandlerTest.java
- src/test/java/it/pagopa/transactions/projections/handlers/CancellationRequestProjectionHandlerTests.java
- src/test/java/it/pagopa/transactions/projections/handlers/ClosureErrorProjectionHandlerTest.java
- src/test/java/it/pagopa/transactions/projections/handlers/ClosureSendProjectionHandlerTests.java
- src/test/java/it/pagopa/transactions/projections/handlers/TransactionUserReceiptProjectionHandlerTest.java
- src/test/java/it/pagopa/transactions/services/TransactionServiceTests.java
- src/test/java/it/pagopa/transactions/utils/AuthRequestDataUtilsTest.java
dependOn https://github.com/pagopa/pagopa-ecommerce-commons/pull/75
Added during **PATCH** the saving of the rrn both in the view and into transactionAuthorizationEvent.
Saved in PATCH phase the RRN field value for VPOS payments. The field is optional
The value has been saved both on the transaction view and in the authorization completion event, to allow recovery during the call to the closePayment and sendPaymentResult for sending the mail
The tests were carried out locally
> CHK-1428-management-rrn

- src/main/resources/application.properties
Change mongo readPreference to `primaryPreferred`
With this mode all read operations will be redirect to primary partition if available with fallback on secondary ones.
The `maxStalenessSeconds` parameter is set to it's the minimum value of 90 seconds in order to block reads from a replica older that 90 seconds
See https://learn.microsoft.com/en-us/azure/cosmos-db/mongodb/readpreference-global-distribution#read-using-read-preference-mode
Those modifications are needed in order to redirect all read operations to the primary replica and lower the required consistency level
> feat: specify mongo read preference mode

- pom.xml
- src/main/java/it/pagopa/transactions/commands/handlers/TransactionActivateHandler.java
- src/main/java/it/pagopa/transactions/projections/handlers/AuthorizationUpdateProjectionHandler.java
- src/main/java/it/pagopa/transactions/projections/handlers/TransactionsActivationProjectionHandler.java
- src/main/java/it/pagopa/transactions/services/TransactionsService.java
- src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
- src/test/java/it/pagopa/transactions/commands/handlers/TransactionInitializerHandlerTest.java
- src/test/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizizationHandlerTest.java
- src/test/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandlerTest.java
- src/test/java/it/pagopa/transactions/commands/handlers/TransactionUpdateAuthorizationHandlerTest.java
- src/test/java/it/pagopa/transactions/commands/handlers/TransactionsActivationProjectionHandlerTest.java
- src/test/java/it/pagopa/transactions/documents/TransactionDocumentTest.java
- src/test/java/it/pagopa/transactions/projections/handlers/AuthorizationUpdateProjectionHandlerTest.java
- src/test/java/it/pagopa/transactions/services/TransactionServiceTest.java
- src/test/java/it/pagopa/transactions/services/TransactionServiceTests.java
Depends on https://github.com/pagopa/pagopa-ecommerce-commons/pull/84
Add configured payment token validity time into TransactionActivatedEvent
Payment token validity time is used by event dispatcher to perform checks before send close payment retry event
Junit tests
Tests with ecommerce local -> perform a new transaction checking that payment token validity time is correctly valued into transaction activated event
> feat: add payment token validity time into event

- src/main/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandler.java
- src/main/java/it/pagopa/transactions/services/TransactionsService.java
- src/test/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandlerTest.java
- src/test/java/it/pagopa/transactions/services/TransactionServiceTests.java
Added a new projectionHandler for handling view update at **REFUND_REQUESTED**.
Updated transaction refund logic, specifically:
- In case of an unrecoverable error of the closePayment request you have to perform a transaction refund and update to view to **REFUND_REQUESTED**.
- In case of a recoverable error of the closePayment request you have to add the event in the retry queue and update the view state to **CLOSURE_ERROR**.
- In case of closePayment with a KO by the node if the transaction was authorized by the **PGS** a refund request must be made and the view updated to **REFUND_REQUESTED**.
-  In case of closePayment with a KO by the node if the transaction was not authorized by the **PGS** update the view to **UNAUTHORIZED**..
- In case of closePayment OK by the node you have to …
> CHK-1301-refund_requested_optional

- src/main/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandler.java
- src/main/java/it/pagopa/transactions/projections/handlers/ClosureErrorProjectionHandler.java
- src/main/java/it/pagopa/transactions/projections/handlers/RefundRequestProjectionHandler.java
- src/main/java/it/pagopa/transactions/services/TransactionsService.java
- src/test/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandlerTest.java
- src/test/java/it/pagopa/transactions/projections/handlers/ClosureErrorProjectionHandlerTest.java
- src/test/java/it/pagopa/transactions/projections/handlers/RefundRequestProjectionHandlerTests.java
- src/test/java/it/pagopa/transactions/services/TransactionServiceTests.java
Added a new projectionHandler for handling view update at **REFUND_REQUESTED**.
Updated transaction refund logic, specifically:
- In case of an unrecoverable error of the closePayment request you have to perform a transaction refund and update to view to **REFUND_REQUESTED**.
- In case of a recoverable error of the closePayment request you have to add the event in the retry queue and update the view state to **CLOSURE_ERROR**.
- In case of closePayment with a KO by the node if the transaction was authorized by the **PGS** a refund request must be made and the view updated to **REFUND_REQUESTED**.
-  In case of closePayment with a KO by the node if the transaction was not authorized by the **PGS** update the view to **UNAUTHORIZED**..
- In case of closePayment OK by the node you have to …
> CHK-1301-refund_requested

- src/main/java/it/pagopa/transactions/utils/NodoOperations.java
- src/test/java/it/pagopa/transactions/utils/NodoOperationsTest.java
After the activation process of a payment notice the input data were used to to populate the redis cache and the view. The solution proposed with this PR uses the data obtained from the nodoActivation response.  
- Update amount from request to nodoActivation rsponse
- Get correct and updated amount
- Unit
> [CHK-1482] fix: set notice amount from nodoActivation response

- pom.xml
- src/main/java/it/pagopa/transactions/projections/handlers/ClosureSendProjectionHandler.java
- src/test/java/it/pagopa/transactions/projections/handlers/ClosureSendProjectionHandlerTests.java
Value sendPaymentResultOutcome with NOT_RECEIVED when the received close payment response outcome is OK
Those modifications are needed in order to value transactions-view sendPaymentResultOutcome according to the fact that a send payment result is expected to be received or not
Junit tests + tests with ecommerce local
> feat(view): sendPaymentResult outcome NOT_RECEIVED

- src/main/java/it/pagopa/transactions/commands/handlers/TransactionActivateHandler.java
- src/main/java/it/pagopa/transactions/utils/NodoOperations.java
- src/test/java/it/pagopa/transactions/commands/handlers/TransactionInitializerHandlerTest.java
- src/test/java/it/pagopa/transactions/utils/NodoOperationsTest.java
Propagate dueDate saved during verification process into cache informations saved after Nodo activate call.
In the current transaction activation flow, due date is overridden by transaction service that set this field forcibly to null.
This way, a new verification performed after transaction activation, that will not communicate with Nodo because of cache hit, will return a response without the dueDate field valued
Junit tests
> [CHK-1692] fix(activation): propagate verification due date

- pom.xml
- src/main/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandler.java
- src/test/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandlerTest.java
Change transaction details transactionStatus field from "Autorizzato" to "Confermato"
Update constant value in closure handler
This PR address some bizEvent bounds
Junit tests has been edited and ran
> [CHK-1693] update transaction status constant

- .devops/deploy-pipelines.yml
Fix prod manual approval task dependencies
This modification is needed in order to perform api test on UAT green instance before prod manual task approval
> fix(deploy-pipeline): prod manual approval depends on green api tests

- pom.xml
- src/main/java/it/pagopa/transactions/commands/handlers/TransactionActivateHandler.java
- src/main/java/it/pagopa/transactions/utils/NodoOperations.java
- src/main/java/it/pagopa/transactions/utils/OpenTelemetryUtils.java
- src/test/java/it/pagopa/transactions/commands/handlers/TransactionInitializerHandlerTest.java
- src/test/java/it/pagopa/transactions/utils/NodoOperationsTest.java
- src/test/java/it/pagopa/transactions/utils/OpenTelemetryUtilsTest.java
1. Add logic for add open telemetry span during a transaction
2. Add span for trace Nodo fault codes received during transaction activation
3. Convert span creation logic for repeated activations for the same RptId from apm to open telemetry
Those modifications are needed to monitor Nodo fault codes received during transaction activation process and for monitor transaction payment token validity time left for re-activated transactions
Junit tests + test in dev enviroment with check on Kibana transactions
Span details for an error received from Nodo on activatePaymentNoticeV2 call
> feat(monitoring): trace Nodo fault code into custom open telemetry span

- src/main/java/it/pagopa/transactions/utils/AuthRequestDataUtils.java
- src/test/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandlerTest.java
- src/test/java/it/pagopa/transactions/commands/handlers/TransactionUpdateAuthorizationHandlerTest.java
- src/test/java/it/pagopa/transactions/utils/AuthRequestDataUtilsTest.java
- base64 transactionId as rrn for xpay 
The RRN field of `closePayment` in case of xpay payments are the first 6 byte of the `idTransaction`. 
The goal of this PR is to define the `RRN` to be passed to `closePayement` as the `idTransaction` in Base64 (according to https://github.com/pagopa/pagopa-ecommerce-transactions-service/blob/main/src/main/java/it/pagopa/transactions/utils/UUIDUtils.java) as it is passed to xpay in the authorization step (ie the order number). 
This makes it possible to reconcile xpay psp/acquirer payments.
> feat(closepayment): CHK-1769 base64 transactionId as rrn for xpay

- pom.xml
- src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandlerCommon.java
- src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionActivateHandler.java
- src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
- src/main/java/it/pagopa/transactions/utils/NodoOperations.java
- src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandlerTest.java
- src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
- src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionsActivationProjectionHandlerTest.java
Depends on https://github.com/pagopa/pagopa-ecommerce-commons/pull/149
Add logic to save sessionId received into confirmPayment NPG response.
This response field is optional so it's saved if received, null value is used otherwise.
This optional field, once received, is the one that must be used for calling NPG getState api.
Junit tests + local test with eCommerce local
> feat: [CHK-2004] - save session id returned in NPG confirm payment

- api-spec/v1/transactions-api.yaml
- pom.xml
- src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionUpdateAuthorizationHandler.java
- src/main/java/it/pagopa/transactions/projections/handlers/v2/AuthorizationUpdateProjectionHandler.java
- src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
- src/main/java/it/pagopa/transactions/utils/AuthRequestDataUtils.java
- src/test/java/it/pagopa/transactions/projections/handlers/v2/AuthorizationUpdateProjectionHandlerTest.java
- src/test/java/it/pagopa/transactions/utils/AuthRequestDataUtilsTest.java
Depends on https://github.com/pagopa/pagopa-ecommerce-commons/pull/174
Add `gatewayAuthorizationStatus` field into transaction view and `GET transactions` response body.
This field is valued with payment gateway status received into `PATCH authorizations` requests.
Add handling for NPG error code saving this information into AUTHORIZATION_COMPLETED events and returned into GET transactions api call.
Both error code and gateway authorization status allow to perform authorization outcome to proper error to be shown to the final user (such as invalid card data and so on) 
Junit tests + local tests with eCommerce local
> feat: NPG error code mapping

- pom.xml
* marked dependency `netty-resolver-dns-native-macos` with test scope
The dependency was needed for macOS on ARM arch and was included unconditionally, but it causes a memory leak of non-heap memory in Linux hosts.
Deployment in dev environment and monitoring on memory.
> [CHK-2334] fix(deps): mark `netty-resolver-dns-native-macos` dependency for test only as it causes memleak in prod

- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
- pom.xml
- src/main/java/it/pagopa/transactions/client/NodeForPspClient.java
- src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionSendClosureHandler.java
- src/test/java/it/pagopa/transactions/client/NodeForPspClientTest.java
- src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionSendClosureHandlerTest.java
- update closureHandler
- increase nodo client timeout
The goal of the PR is to initiate a refund during the sending of a closePayment only if the status code 422 is encountered, with the following description:
```
Node did not receive RPT yet
```
waiting a structured error code from the node.
Consequently, unlike before, in the event of a 4xx error, the transaction status remains unchanged at `AUTHORIZATION_COMLETED`, and the API returns a 502 response.
> Chk-2465: restrict refund in closure handler

- src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
- src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandlerCommon.java
- src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandler.java
- src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
- src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
- src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandlerTest.java
- src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
depend on https://github.com/pagopa/pagopa-ecommerce-transactions-service/pull/420
Used the correlationId saved in the activation event during the call flow to NPG.
The change was made to use the same correlationId in all calls to NPG
> [CHK 2443] used correlation saved into activated event into NPG call

- pom.xml
- src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestUserReceiptHandler.java
- src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestUserReceiptHandlerTest.java
Porting of feature flag for accept send payment result after transaction expiration 
This modification is required in order to accept send payment result received after transaction expiration also for event v2 transactions
Junit tests
> feat(ff): send payment result after expiration for v2 events

- src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
- src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java
Fixed error code mapping in case of missing AUTHORIZATION_REQUESTED event during a PATCH auth request processing mapping it to 409 instead of 404
This modification is needed to properly map error response code in case a PATCH auth request is performed before an authorization request
Junit tests
> fix: error mapping for patch auth request with missing auth requested event

- api-spec/v2/transactions-api.yaml
- pom.xml
- src/main/java/it/pagopa/transactions/commands/TransactionActivateCommand.java
- src/main/java/it/pagopa/transactions/commands/data/NewTransactionRequestData.java
- src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionActivateHandler.java
- src/main/java/it/pagopa/transactions/controllers/v2/TransactionsController.java
- src/main/java/it/pagopa/transactions/projections/handlers/v2/AuthorizationUpdateProjectionHandler.java
- src/main/java/it/pagopa/transactions/projections/handlers/v2/TransactionsActivationProjectionHandler.java
- src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
- src/main/java/it/pagopa/transactions/services/v2/TransactionsService.java
- src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionActivateHandlerTest.java
- src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionActivateHandlerTest.java
- src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
- src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionUpdateAuthorizationHandlerTest.java
- src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionsActivationProjectionHandlerTest.java
- src/test/java/it/pagopa/transactions/controllers/v2/TransactionsControllerTest.java
- src/test/java/it/pagopa/transactions/projections/handlers/v2/AuthorizationUpdateProjectionHandlerTest.java
- src/test/java/it/pagopa/transactions/projections/handlers/v2/CancellationRequestProjectionHandlerTests.java
- src/test/java/it/pagopa/transactions/projections/handlers/v2/ClosureRequestedProjectionHandlerTests.java
- src/test/java/it/pagopa/transactions/projections/handlers/v2/TransactionUserReceiptProjectionHandlerTest.java
- src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTest.java
- src/test/java/it/pagopa/transactions/services/v2/CircuitBreakerTest.java
- src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTest.java
- src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTests.java
Add logic to save user id if received into POST transaction `x-user-id` header
This logic is required in order to trace user that perform the transaction for registered payments
junit tests + test in DEV environment
Depends on pagopa/pagopa-ecommerce-commons#189
> feat: save user id into transaction activated event

- api-spec/v2.1/transactions-api.yaml
- pom.xml
- src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
- src/main/java/it/pagopa/transactions/services/v2/TransactionsService.java
- src/main/java/it/pagopa/transactions/services/v2_1/TransactionsService.java
- src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java
- src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTest.java
- src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTests.java
- src/test/java/it/pagopa/transactions/services/v2_1/TransactionServiceTest.java
This PR includes the groundwork from pagopa/pagopa-ecommerce-commons#214
The returned field `clientId` is mapped to `CHECKOUT_CART` in order to make the new `WISP` client backward compatible with the current API
Depends on pagopa/pagopa-ecommerce-commons#214
> [CHK-3119] feat: map `WISP_REDIRECT` client id when creating transactions to `CHECKOUT_CART`

- src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
- src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
* truncate `paName` field to 70 chars
This change fixes a discrepancy between Checkout Redirect `paName` length (max length 70) and Nodo's `activate` `companyName` field (max length 140).
Now, a `companyName` field that is longer than 70 chars gets truncated to 67 chars plus an ellipsis `...`.
Depends on pagopa/pagopa-mock-ec#67
> [CHK-3094] fix(redirect): truncate `paName` field to 70 chars

- src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
- src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
- src/main/resources/application.yml
- src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
- src/test/java/it/pagopa/transactions/controllers/v1/TransactionsControllerTest.java
- src/test/java/it/pagopa/transactions/services/v1/CircuitBreakerTest.java
Move lock from ahead to just before call gateway for auth request
This modification will leave retry attempts for all errors that could happen before call the payment gateway, acquiring lock for authorization just before communication with gateway is performed
> fix: move lock before interacting with gateway

- .devops/code-review-pipelines.yml
- pom.xml
- src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
- src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
Depends on https://github.com/pagopa/pagopa-ecommerce-commons/pull/220
Open auth request expiration queue flux to all auth request events, in order to save last usage method for user from app IO.
- write `walletId` in auth request gateway data
- write auth-request event also for nonNPG payment flow to use it in event-dispatcher queue message receiver and save last method used
- update junit tests
> [CHK-3291] Save last payment method by user

- src/main/java/it/pagopa/transactions/utils/NodoOperations.java
- src/test/java/it/pagopa/transactions/utils/NodoOperationsTest.java
depends on https://github.com/pagopa/io-pagopa-node-mock/pull/59
depends on https://github.com/pagopa/pagopa-ecommerce-local/pull/177
- enrich transfer in activateV2Response
This PR implements a new feature that enrich payment transfer information based on specified transfer data and associated metadata. The primary goal is to create transfer lists that facilitate the management of conventions, which will be utilized during the fee retrieval process (GEC).
> feat(nodo-activate): CHK-3531 enrich transfer with conventions

- src/main/java/it/pagopa/transactions/utils/NodoOperations.java
- src/test/java/it/pagopa/transactions/utils/NodoOperationsTest.java
- use creditorReferenceId in transfer for convention
The goal of this PR is to use `creditorReferenceId` instead `66666666666` in transfer only for convention (response metadata activatePaymentNotice).
> feat(convention): CHK-3531 use creditorRefernceId in tranfer for convention

- src/main/java/it/pagopa/transactions/utils/NodoOperations.java
- src/test/java/it/pagopa/transactions/utils/NodoOperationsTest.java
- use `fiscalCodePA` (activatePaymentV2 response) in transfer for conventions
The goal of this PR is to use `fiscalCodePA`  instead `creditorReferenceId` in transfer only for convention (response metadata activatePaymentNotice).
> fix: primary fiscal code for convention

- src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandlerCommon.java
- Fix double query param in auth-request call
During the authorization phase, the transaction service generated an authorization URL containing two query parameters with the same key. This PR aims to eliminate this duplication.
Unit test
> [MAIN-4] Remove redundant query param

- src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
log authorization request id and transaction id for the authorization request operation when saving the event
- add log related to the authorization request save event op
We needed to bind the transaction id and the authorization request id to better track the operation in the logs
> chore: PPABV-77 log authorization request id and transaction id for authorization request operation

- src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestUserReceiptHandler.java
- src/main/java/it/pagopa/transactions/exceptions/InvalidStatusException.java
- src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestUserReceiptHandlerTest.java
- src/test/java/it/pagopa/transactions/services/v1/CircuitBreakerTest.java
Adds a retry policy when addUserReceipt is invoked while the transaction state is CLOSURE_REQUESTED
The addUserReceipt function might be invoked before the eventDispatcher has updated the transaction state. Retrying could help prevent disruptions in the event flow.
Unit test and local integration test
> [PIDM-134] Handle retry on add user receipt

- .devops/azure-templates/helm-microservice-chart-deploy.yml
- .devops/deploy-pipelines.yml
- helm/Chart.lock
- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
Upgrade to helm chart 7 performing the following modifications:
- chat version update from 2.8.0 to 7.4.0
- canaryDelivery parameter update to the new template (adding canary section)
- add workload identity refs for each environment specifying the azure workload identity client id and service account name for each env
Those modification are needed in order to make ecommerce transactions service use workload identities instead of deprecated pod identity
Not yet
expected)
> feat: [CHK-3777] helm chart v7 and workload identities
