pagopa/pagopa-ecommerce-transactions-service

pom.xml
src/main/java/it/pagopa/transactions/documents/Transaction.java
src/main/java/it/pagopa/transactions/documents/TransactionEvent.java
src/main/java/it/pagopa/transactions/documents/TransactionInitData.java
src/main/java/it/pagopa/transactions/handlers/EventHandler.java
src/main/java/it/pagopa/transactions/handlers/impl/TransactionInitEventHandler.java
src/main/java/it/pagopa/transactions/repositories/TransactionsEventStoreRepository.java
src/main/java/it/pagopa/transactions/repositories/TransactionsViewRepository.java
src/main/java/it/pagopa/transactions/utils/TransactionEventCode.java
src/main/java/it/pagopa/transactions/utils/TransactionStatus.java

- add mongodb reactive deps;
- add reactive repository and entity for eventStore;
- add reactive repository and entity for view;
- add simple event handler (to improve);

[CHK-358] eventstore and view handlers

---

Dockerfile

OpenJDK `*-alpine` images are not officially supported, and are built only for [beta and early access versions of OpenJDK](https://github.com/docker-library/docs/blob/master/openjdk/README.md#openjdkversion-alpine).
* Use stable instead of early access OpenJDK build in Docker
Local build with Docker

fix(docker): fix openjdk base image

---

pom.xml
src/main/java/it/pagopa/transactions/controllers/TransactionsController.java

* Change server from tomcat to netty

[CHK-376] Change server from tomcat to netty

---

src/main/java/it/pagopa/transactions/client/EcommerceSessionsClient.java
src/main/java/it/pagopa/transactions/configurations/WebClientsConfig.java

- Refactor `pagopa-ecommerce-session-service` client

[CHK-374] Refactor ecommerce-session-service client

---

src/main/java/it/pagopa/transactions/utils/soap/JaxbContextContainer.java

fix: update PACKAGE_NODE_FOR_PSP

---

lombok.config
src/main/java/it/pagopa/transactions/commands/TransactionsCommandCode.java
src/main/java/it/pagopa/transactions/model/IdempotencyKey.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionInitializerHandlerTest.java
src/test/java/it/pagopa/transactions/controllers/TransactionsControllerTest.java
src/test/java/it/pagopa/transactions/model/IdempotencyKeyTest.java
src/test/java/it/pagopa/transactions/model/RptIdTest.java
src/test/java/it/pagopa/transactions/services/TransactionServiceTests.java

[CHK-383] improve test coverage

---

pom.xml
src/main/java/it/pagopa/transactions/commands/TransactionInitializeCommand.java
src/main/java/it/pagopa/transactions/commands/TransactionsCommand.java
src/main/java/it/pagopa/transactions/commands/handlers/TransactionInizializeHandler.java
src/main/java/it/pagopa/transactions/projections/handlers/TransactionsProjectionHandler.java
src/main/java/it/pagopa/transactions/services/TransactionsService.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionInitializerHandlerTest.java
src/test/java/it/pagopa/transactions/projections/handlers/TransactionProjectionHandlerTest.java
src/test/java/it/pagopa/transactions/services/TransactionServiceTest.java

* Refactor `TransactionsProjectionHandler` with new transaction aggregate
* Make command handlers more type safe using sealed classes
The code driving the API has been updated by using the new DDD aggregates introduced in #23

[CHK-429] Update API implementation using new DDD aggregates

---

api-spec/api.yaml
docker-compose.yml
pom.xml
src/main/java/it/pagopa/transactions/controllers/TransactionsController.java
src/main/java/it/pagopa/transactions/documents/Transaction.java
src/main/java/it/pagopa/transactions/domain/IdempotencyKey.java
src/main/java/it/pagopa/transactions/repositories/TransactionsViewRepository.java
src/main/java/it/pagopa/transactions/services/TransactionsService.java
src/test/java/it/pagopa/transactions/controllers/TransactionsControllerTest.java
src/test/java/it/pagopa/transactions/domain/IdempotencyKeyTest.java
src/test/java/it/pagopa/transactions/services/TransactionServiceTest.java
src/test/java/it/pagopa/transactions/services/TransactionServiceTests.java

[CHK-436] Add payment authorization request API

---

helm/Chart.lock
helm/Chart.yaml
helm/values-dev.yaml

- update helm dep
- add ingress creation
- update redis host
- update deployment resources request/limit

feat: update helm chart

---

api-spec/api.yaml
src/main/java/it/pagopa/transactions/controllers/TransactionsController.java

* Add authorization status update api

[CHK-487] Add authorization status update api

---

pom.xml
src/main/java/it/pagopa/transactions/client/NodeForPspClient.java
src/main/java/it/pagopa/transactions/configurations/WebClientsConfig.java

* Fix Node WebClient configuration

Fix Node WebClient configuration

---

api-spec/payment-requests-api.yaml
pom.xml
src/main/java/it/pagopa/transactions/client/NodeForPspClient.java
src/main/java/it/pagopa/transactions/client/NodoPerPspClient.java
src/main/java/it/pagopa/transactions/controllers/PaymentRequestsController.java
src/test/java/it/pagopa/transactions/client/NodeForPspClientTest.java
src/test/java/it/pagopa/transactions/client/NodoPerPspClientTest.java
src/test/java/it/pagopa/transactions/controllers/PaymentRequestsControllerTest.java

- Add verificaRPT client
- Add verifyPaymentNotice client
- Add new PaymentRequestsControllers to verify API

[CHK-582] add verificaRPT and verifyPaymentNotice

---

pom.xml

- Update file reference for client generation in pom

Fix openapi file refs in pom.xml

---

api-spec/payment-requests-api.yaml
src/main/java/it/pagopa/transactions/commands/handlers/TransactionInizializeHandler.java
src/main/java/it/pagopa/transactions/repositories/PaymentRequestInfo.java
src/main/java/it/pagopa/transactions/services/PaymentRequestsService.java
src/main/java/it/pagopa/transactions/utils/NodoOperations.java
src/main/resources/application.properties
src/test/java/it/pagopa/transactions/commands/handlers/TransactionInitializerHandlerTest.java
src/test/java/it/pagopa/transactions/services/PaymentRequestsServiceTest.java
src/test/java/it/pagopa/transactions/utils/NodoOperationsTest.java

- renamed `paTaxCode` in `paFiscalCode`;
- converted amount from nodo as euro cents ( 10,91 -> 1091 ); 
The goal of this PR is to refactor given by observations made during the design review, in particular to manage the amounts retrieved from the `nodo pagoPA` as euro cents and to rename the `taxCode` field with `fiscalCode`.
run unit tests and check amounts in APIs response with `ecommerce local`

Minor fix post sprint review

---

pom.xml

update pom xml
set new source for openapi.json file for notification service

update openapi.json.tpl reference

---

.devops/deploy-pipelines.yml
api-spec/transactions-api.yaml
helm/Chart.yaml
helm/values-dev.yaml
helm/values-uat.yaml
pom.xml
src/main/java/it/pagopa/transactions/commands/handlers/TransactionActivateHandler.java
src/main/java/it/pagopa/transactions/configurations/NodoConfig.java
src/main/java/it/pagopa/transactions/configurations/WebClientsConfig.java
src/main/java/it/pagopa/transactions/controllers/TransactionsController.java
src/main/java/it/pagopa/transactions/documents/TransactionActivationRequestedEvent.java
src/main/java/it/pagopa/transactions/repositories/TransactionsActivationRequestedEventStoreRepository.java
src/main/java/it/pagopa/transactions/repositories/TransactionsEventStoreRepository.java
src/main/java/it/pagopa/transactions/services/TransactionsService.java
src/main/java/it/pagopa/transactions/utils/NodoConnectionString.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionInitializerHandlerTest.java
src/test/java/it/pagopa/transactions/services/TransactionServiceTests.java

- update api to handle `Nodo cdInfoWisp` with `paymentContextCode` and not `transactionId`;
- disable `FAIL_ON_UNKNOWN_PROPERTIES` for nodoPerPm client;
The goal of this PR is to update the APIto handle `Nodo cdInfoWisp`, in particular to create the activation event by searching for the last activation event requested given a `paymentContextCode`.

feat: activation result by paymentContextCode

---

pom.xml
src/main/java/it/pagopa/transactions/client/NotificationsServiceClient.java
src/main/java/it/pagopa/transactions/commands/handlers/TransactionUpdateStatusHandler.java
src/main/resources/template-schemas/ko.json
src/test/java/it/pagopa/transactions/client/NotificationsServiceClientTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionUpdateStatusHandlerTest.java

[CHK-604] feat(email): add sending of KO template when receiving KO outcome from Nodo

---

Dockerfile
applicationinsights.json
helm/values-dev.yaml
helm/values-uat.yaml

[CHK-676] Add AI to Ecommerse Transaction

---

.devops/deploy-pipelines.yml

fix source branch for deploy as main

---

helm/values-uat.yaml

update memory allocation to 512

---

src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java

* update client with string in `idTransaction` during authorization
Depends on pagopa/pagopa-infra#461

[CHK-673] refactor(payment-gateway-service): update client with string in `idTransaction` during authorization

---

pom.xml
src/main/java/it/pagopa/transactions/controllers/PaymentRequestsController.java
src/main/java/it/pagopa/transactions/controllers/TransactionsController.java
src/test/java/it/pagopa/transactions/controllers/TransactionsControllerTest.java

[CHK-482] fix(openapi): add missing dependency to make bean validation work

---

pom.xml
src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
src/main/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandler.java
src/main/java/it/pagopa/transactions/configurations/WebClientsConfig.java
src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandlerTest.java

- euro cents to euro for amount used in `closepayment`;
The goal of this PR is to use euro instead eurocents for `closePayment`, so 4305 -> 43.05.

fix: amount for closepayment

---

src/main/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandler.java
src/main/java/it/pagopa/transactions/utils/EuroUtils.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandlerTest.java

feat: fee as euro insted eurocents in closepayment

---

src/main/java/it/pagopa/transactions/client/EcommercePaymentInstrumentsClient.java
src/main/java/it/pagopa/transactions/services/TransactionsService.java
src/test/java/it/pagopa/transactions/client/EcommercePaymentMethodsClientTest.java
src/test/java/it/pagopa/transactions/client/EcommerceSessionsClientTest.java
src/test/java/it/pagopa/transactions/services/TransactionServiceTests.java

- Change payment-methods-service API used for querying PSPs
- Get PSPs related to a specific payment-method

[CHK-702] fix: payment-method-service API for PSPs

---

pom.xml

fix: update sepc for notifications

---

.devops/code-review-pipelines.yml

Added inside the code riview pipelines a new stage called Integration test to run the pagopa-ecommerce-local docker-compose and execute the rest api calls for check if the service is available.
The change was made to allow a PR check on the regression caused to the ecommerce project by the developer's changes.
After triggering the PR the new stage is successfully completed.

Added new stage for execute integration test into code review pipelines

---

.devops/code-review-pipelines.yml

Modified in the code review pipeline the principle branch reference for the ecommerce-local project.
This change was necessary because we needed to update the main branch of the pagopa-ecommerce local project in the code review pipeline.
Code review pipeline execution.

Changed into code review pipeline the ecommerce-local ref branch

---

api-spec/transactions-api.yaml
src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
src/main/java/it/pagopa/transactions/commands/data/AuthorizationRequestData.java
src/main/java/it/pagopa/transactions/controllers/TransactionsController.java
src/main/java/it/pagopa/transactions/exceptions/InvalidRequestException.java
src/main/java/it/pagopa/transactions/services/TransactionsService.java
src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizizationHandlerTest.java
src/test/java/it/pagopa/transactions/controllers/TransactionsControllerTest.java
src/test/java/it/pagopa/transactions/services/TransactionServiceTests.java

Propagate card authorization informations to the TransactionRequestAuthorizationHandler
Card informations such as pan, cvv etc are necessary in order to perform card payment authorization
Junit test

[CHK-826] - feat: set cardholder info into AuthorizationRequestData

---

src/main/java/it/pagopa/transactions/controllers/TransactionsController.java
src/test/java/it/pagopa/transactions/controllers/TransactionsControllerTest.java

Add constraint validation exception into bad request exception handler
This change is required in order to map ConstraintValidationException as 400 Bad request

[CHK-826] - fix: add Transaction ConstraintViolationException handling

---

.devops/code-review-pipelines.yml

* remove need for `global-transaction-service.env` file in `pagopa-ecommerce-local`

refactor(cr-pipeline): remove need for `global-transaction-service.env` file in `pagopa-ecommerce-local`

---

CODEOWNERS

fix: team codewner

---

pom.xml
src/main/java/it/pagopa/transactions/commands/handlers/TransactionActivateHandler.java
src/main/java/it/pagopa/transactions/commands/handlers/TransactionActivateResultHandler.java
src/main/java/it/pagopa/transactions/commands/handlers/TransactionAddUserReceiptHandler.java
src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandler.java
src/main/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandler.java
src/main/java/it/pagopa/transactions/projections/handlers/AuthorizationUpdateProjectionHandler.java
src/main/java/it/pagopa/transactions/projections/handlers/TransactionUserReceiptProjectionHandler.java
src/main/java/it/pagopa/transactions/projections/handlers/TransactionsActivationProjectionHandler.java
src/main/java/it/pagopa/transactions/projections/handlers/TransactionsActivationRequestedProjectionHandler.java
src/main/java/it/pagopa/transactions/services/TransactionsService.java
src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionActivateResultHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionAddUserReceiptHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionInitializerHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizizationHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionUpdateAuthorizationHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionsActivationProjectionHandlerTest.java
src/test/java/it/pagopa/transactions/documents/TransactionDocumentTest.java
src/test/java/it/pagopa/transactions/projections/handlers/AuthorizationUpdateProjectionHandlerTest.java
src/test/java/it/pagopa/transactions/projections/handlers/ClosureErrorProjectionHandlerTest.java
src/test/java/it/pagopa/transactions/projections/handlers/TransactionProjectionHandlerTest.java
src/test/java/it/pagopa/transactions/projections/handlers/TransactionUserReceiptProjectionHandlerTest.java
src/test/java/it/pagopa/transactions/services/TransactionServiceTest.java
src/test/java/it/pagopa/transactions/services/TransactionServiceTests.java

[CHK-893] updte transaction service to fit new TransactionActivationRequestData schema

---

Dockerfile

Fix dockerfile to include ecplipse codestyle
Modification needed in order to perform docker build corretly
Local docker build

fix: docker file

---

api-spec/transactions-api.yaml
src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
src/test/java/it/pagopa/transactions/services/TransactionServiceTests.java

This PR changes the expiry date format for credit cards authorization requests from an ISO date to a `YYYYMM` string format.
This change was motivated by the fact that payment gateways for credit cards that will be emploed by eCommerce use `YYYYMM` as the expiry date format.

[CHK-920] refactor(api): change card expiry date format from date to `YYYYMM`

---

src/test/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizizationHandlerTest.java

Fix unit tests after main merge
Fix broken unit tests after main branch merge
Local build

[CHK-918] fix: unit tests

---

.devops/code-review-pipelines.yml
api-spec/transactions-api.yaml
helm/values-dev.yaml
src/main/java/it/pagopa/transactions/controllers/TransactionsController.java
src/main/java/it/pagopa/transactions/services/TransactionsService.java
src/test/java/it/pagopa/transactions/controllers/TransactionsControllerTest.java
src/test/java/it/pagopa/transactions/services/TransactionServiceTest.java

Add POST transactions 'X-Client-Id' optional header evaluation to set transaction origin into transaction events.
This modification is need in order to set transaction origin value taking information from the request origin
Local test

Chk 924 transaction origin header

---

api-spec/transactions-api.yaml
pom.xml
src/main/java/it/pagopa/transactions/commands/TransactionActivateCommand.java
src/main/java/it/pagopa/transactions/commands/handlers/TransactionActivateHandler.java
src/main/java/it/pagopa/transactions/commands/handlers/TransactionActivateResultHandler.java
src/main/java/it/pagopa/transactions/projections/handlers/AuthorizationUpdateProjectionHandler.java
src/main/java/it/pagopa/transactions/projections/handlers/TransactionUserReceiptProjectionHandler.java
src/main/java/it/pagopa/transactions/projections/handlers/TransactionsActivationProjectionHandler.java
src/main/java/it/pagopa/transactions/projections/handlers/TransactionsActivationRequestedProjectionHandler.java
src/main/java/it/pagopa/transactions/services/TransactionsService.java
src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionActivateResultHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionAddUserReceiptHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionInitializerHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizizationHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionUpdateAuthorizationHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionsActivationProjectionHandlerTest.java
src/test/java/it/pagopa/transactions/documents/TransactionDocumentTest.java
src/test/java/it/pagopa/transactions/projections/handlers/AuthorizationUpdateProjectionHandlerTest.java
src/test/java/it/pagopa/transactions/projections/handlers/ClosureErrorProjectionHandlerTest.java
src/test/java/it/pagopa/transactions/projections/handlers/TransactionProjectionHandlerTest.java
src/test/java/it/pagopa/transactions/projections/handlers/TransactionUserReceiptProjectionHandlerTest.java
src/test/java/it/pagopa/transactions/services/TransactionServiceTest.java
src/test/java/it/pagopa/transactions/services/TransactionServiceTests.java

1. Update commons library version with the latest one (refactored document origin to clientId)
2. Refactored origin field to clientId into openapi specifications
Those modifications are needed in order to refactor `origin` to a meaningful `clientId` name
Local test (using ecommerce local and performing a new transactions checking stored events and returned responses)

fix: refactoring origin to client id + commons update

---

pom.xml
src/main/java/it/pagopa/transactions/commands/handlers/TransactionActivateHandler.java
src/main/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandler.java
src/main/java/it/pagopa/transactions/services/TransactionsService.java
src/main/java/it/pagopa/transactions/utils/NodoOperations.java
src/test/java/it/pagopa/transactions/utils/NodoOperationsTest.java

* fix Redis population with null values in case of cache miss
This PR fixes an issue occurring when calling `POST /transactions` directly or when encountering a cache miss when invoking this endpoint. 
Previously, the payment information data saved on Redis was not populated from Nodo's activation response. 
Upon a cache miss `null` values would be saved to Redis and could wreak havoc on later payment flows for the same notice (as the Redis cache would be incorrectly populated).
Depends on: pagopa/pagopa-ecommerce-commons#18
Depends on: pagopa/pagopa-ecommerce-transactions-service#114

[CHK-933] fix(node): fix Redis population with null values in case of cache miss

---

src/main/java/it/pagopa/transactions/utils/NodoOperations.java

Fix transaction amount: conversion between eurocent amount and it's BigDecimal representation is wrong and cents part is lost during conversion
This fix is needed in order to take request amount correctly
local test

fix: transaction amount

---

src/test/java/it/pagopa/transactions/utils/NodoOperationsTest.java

Add missing junit test for amount conversion
Add missing junit tests for amount conversion

[CHK-949] fix: add tests for amount conversion fix

---

helm/values-dev.yaml

Fix methods service path

---

helm/values-dev.yaml

fix: payment-gateway-service path

---

helm/values-dev.yaml
helm/values-uat.yaml

fix: add servicePort for ingress according to helm chart v2

---

helm/values-uat.yaml

fix: delete ports in liveness and add in service

---

helm/values-uat.yaml

Add removed parameter for UAT deploy
Add removed parameter for UAT deployment. This parameter will be definitively removed in a separate PR after UAT deployment

fix: restore parameter for deploy

---

helm/values-uat.yaml

Removed unused parameter
Removed unused parameter

fix: remove unused parameter for deploy

---

src/main/java/it/pagopa/transactions/commands/handlers/TransactionAddUserReceiptHandler.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionAddUserReceiptHandlerTest.java

The goal of the task was to manage the status **CLOUSURE_FAILED** while checking for sending the email to the user.
In particular, the control has been added to allow the sending of the mail even if the transaction is in the **CLOUSURE_FAILED** state because only the **CLOSED** state was managed.
The tests were performed locally.

CHK-1038-transactionAddUserReceiptHandler

---

src/main/java/it/pagopa/transactions/commands/handlers/TransactionAddUserReceiptHandler.java

* make transaction id lower case in payment outcome emails

[CHK-760] refactor(emails): make transaction id lower case in payment outcome emails

---

src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java

- update vpos request according to openapi update, in particular:
- `emailCh`  --> `emailCH`
- `securitycode` --> `securityCode`

fix(spec): update vpos request according spec update

---

helm/values-dev.yaml
helm/values-uat.yaml

Refactored encryption secret value from `email-confidential-data-encryption-key` to `email-encryption-key`
Refactored encryption secret value from `email-confidential-data-encryption-key` to `email-encryption-key`

fix: encryption key secret name refactoring

---

src/main/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandler.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandlerTest.java

Depends on: pagopa/pagopa-ecommerce-scheduler-service#27
Change queue on which send closure events for Nodo response outcome KO.
This modifications are needed in order to send the transaction closure event to the proper queue
Junit test + local tests using ecommerce local

[CHK-1177] feat: send close KO event to activated queue

---

pom.xml
src/main/java/it/pagopa/transactions/commands/handlers/TransactionAddUserReceiptHandler.java
src/main/java/it/pagopa/transactions/projections/handlers/TransactionUserReceiptProjectionHandler.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionAddUserReceiptHandlerTest.java
src/test/java/it/pagopa/transactions/projections/handlers/TransactionUserReceiptProjectionHandlerTest.java
src/test/java/it/pagopa/transactions/services/TransactionServiceTests.java

* update commons version to v0.8.3

[CHK-1170] feat(commons): update commons version to v0.8.3

---

src/main/java/it/pagopa/transactions/services/TransactionsService.java
src/main/java/it/pagopa/transactions/utils/UUIDUtils.java
src/test/java/it/pagopa/transactions/utils/UUIDUtilsTest.java

Handled http status 400 when decoding transactionId. 
Handled http status 400 when decoding transactionId. The service responded with 500

CHK-1150-fix-decode-transactionId

---

pom.xml

Update notifications spec refs into POM reflecting the openapi reference on infra
Update notifications spec refs into POM reflecting the openapi reference on infra
Build and junit tests

fix: change notifications spec refs

---

.devops/deploy-pipelines.yml

Add parameters to skip blue/green deployment into deployment pipeline
Those modifications are needed in order to skip blue/green deployment

fix: skip blue/green deployment

---

src/main/java/it/pagopa/transactions/client/NodeForPspClient.java

- Update `NodeForPspClient` closePayment logging, add outcome

[CHK-1285] fix: Update closePayment logging, add outcome reference

---

pom.xml
src/main/java/it/pagopa/transactions/client/EcommercePaymentMethodsClient.java
src/main/java/it/pagopa/transactions/configurations/WebClientsConfig.java
src/main/java/it/pagopa/transactions/services/TransactionsService.java
src/test/java/it/pagopa/transactions/client/EcommercePaymentMethodsClientTest.java
src/test/java/it/pagopa/transactions/services/TransactionServiceTests.java

Changed the reference to the payment-methods open api, now the code is generated from the open api stored inside the infra repository.
The change was made to allow centralization of the open api specification.

CHK-1238-generate-from-infra

---

src/main/java/it/pagopa/transactions/client/EcommercePaymentMethodsClient.java
src/main/java/it/pagopa/transactions/configurations/WebClientsConfig.java
src/test/java/it/pagopa/transactions/client/EcommercePaymentMethodsClientTest.java

Update code to reflect the new payment method api published on infra
Those modifications are needed in order to make transactions-service compliant to new payment methods api
Junit tests

fix: update payment method api

---

.devops/deploy-pipelines.yml

Add helm repo in case of green deployment skipping blue deployment
Add helm repo in case of green deployment skipping blue deployment

fix: uat deploy pipeline add helm repo

---

.devops/azure-templates/api-tests.yml
.devops/deploy-pipelines.yml

This PR update the devops deploy pipeline adding two new steps of API tests to test the integration of the deployed microservice in the eCommerce environment. The stages test the development deployment, the blue UAT deployment and the green UAT deployment. 
- Add API integration tests in deploy pipeline
- Increase code quality

[CHK-1384] feat: add api tests stage for deploy-pipelines.yml

---

.devops/deploy-pipelines.yml

Fix checkout tests branch to main
Fix checkout tests branch to main

fix: checkout branch

---

src/main/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandler.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandlerTest.java

fix: closePayment request

---

.devops/azure-templates/api-tests.yml
.devops/deploy-pipelines.yml

- Add test-suffix parameters for API test stage in deploy pipeline

[CHK-1384] fix: differentiate test report name

---

pom.xml
src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
src/main/java/it/pagopa/transactions/commands/handlers/TransactionActivateHandler.java
src/main/java/it/pagopa/transactions/projections/handlers/AuthorizationUpdateProjectionHandler.java
src/main/java/it/pagopa/transactions/projections/handlers/TransactionsActivationProjectionHandler.java
src/main/java/it/pagopa/transactions/services/TransactionsService.java
src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizizationHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionUpdateAuthorizationHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionUserCancelHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionsActivationProjectionHandlerTest.java
src/test/java/it/pagopa/transactions/projections/handlers/AuthorizationUpdateProjectionHandlerTest.java
src/test/java/it/pagopa/transactions/services/TransactionServiceTest.java
src/test/java/it/pagopa/transactions/services/TransactionServiceTests.java
src/test/java/it/pagopa/transactions/utils/TransactionsUtilsTest.java

Update commons version to 0.11.0
Refactored transactionId to handle UUID without dashes
Those modification are needed to handle transaction id without dashes in order to have a transaction id lesser than 35 chars
Junit tests, local test (ecommerce commons) and test in DEV environment
expected)

fix: transaction id length

---

pom.xml
src/main/java/it/pagopa/transactions/utils/NodoOperations.java

dependOn https://github.com/pagopa/pagopa-infra/pull/894
Depends on https://github.com/pagopa/pagopa-infra/pull/894  (INFRA → update on specs)
Updated wsdl for the generation of calls to the node to manage the transferCategory returned during activation request.
Managed the rescue of transferCategory useful for the construction of the body of the call to GEC.
The tests were performed locally

CHK-1248-transferCategory

---

src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java

- update pgs client endpoint
The goal of this PR is to use new pgs client method in order to call PGS with new endpoints:
- `xpay/authorizations`
- `vpos/authorizations`

fix: update pgs client endpoint

---

api-spec/transactions-api.yaml

fix: optional rrn in patch ecommerce pgs

---

helm/values-uat.yaml
src/main/resources/application.properties

Parametrize log stacktrace
Parametrize log stacktrace

fix: parametrize log stacktrace

---

src/main/java/it/pagopa/transactions/services/TransactionsService.java
src/main/resources/application.yml

Change circuit breaker associated to get transactions distinguished from the one used for nodo backend
This modification is needed since GET transaction operation does not depends on Nodo operativity

fix: change get transaction circuit breaker

---

Dockerfile
helm/values-dev.yaml
helm/values-uat.yaml
src/main/resources/logback.xml

Configure ELK agent in dockerfile configuration
Remove appinsight hook
Add ELK agent
Add context metadata to log message (waiting for filebeat integration)
This PR is due to have logs available without any cap

[CHK-1468] add elk agent

---

helm/values-uat.yaml

Fixed value of env variable PAYMENT_TOKEN_VALIDITY_TIME for green deployment.
Changed the value of the duration of the payment token for the green version of the deploy in UAT

fix: PAYMENT_TOKEN_VALIDITY_TIME value for green deploy

---

src/main/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandler.java
src/main/java/it/pagopa/transactions/configurations/WebClientsConfig.java
src/test/java/it/pagopa/transactions/client/NodeForPspClientTest.java
src/test/java/it/pagopa/transactions/configurations/WebClientsConfigTest.java

- Remove null-value json properties in node requests
- Add `JsonInclude.Include.NON_NULL` rule to jackson mapper to avoid adding null-value json properties
- Align to Nodo web-services requirements

[CHK-1510] fix: remove null-value json properties in node requests

---

api-spec/transactions-api.yaml
pom.xml

Edit send payment result request body
remove office name and company name from required fields

[CHK-1515] SendPaymentResult: define required fields

---

.devops/deploy-pipelines.yml

feat(kubectl): add KubectlInstaller in uat deploy pipeline

---

src/main/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandler.java
src/main/java/it/pagopa/transactions/commands/handlers/TransactionUpdateAuthorizationHandler.java
src/main/java/it/pagopa/transactions/utils/AuthRequestDataUtils.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandlerTest.java
src/test/java/it/pagopa/transactions/utils/AuthRequestDataUtilsTest.java

- add `rrn` set with `transactionId` in `closePayment` for `xpay` authorizations;
The goal of this PR is to have a `rrn`  set with `transactionId` in `closePayment` for `xpay` authorizations,

feat(closepayment): CHK-1548 add rrn for xpay with transactionId

---

src/main/java/it/pagopa/transactions/projections/handlers/AuthorizationRequestProjectionHandler.java
src/main/java/it/pagopa/transactions/projections/handlers/AuthorizationUpdateProjectionHandler.java
src/test/java/it/pagopa/transactions/projections/handlers/AuthorizationUpdateProjectionHandlerTest.java

Depends on: https://github.com/pagopa/pagopa-ecommerce-commons/pull/82
- Update View with additional info according to [RFC](https://pagopa.atlassian.net/wiki/spaces/I/pages/703857491/Mapping+stato+transazione+-+pagina+di+esito)
- Add additional info for correctly handle "pagina esito" landing page

[CHK-1533] feat: add additional info to view

---

helm/values-prod.yaml

feat(helm): CHK-1539 add helm value for prod

---

api-spec/transactions-api.yaml
src/main/java/it/pagopa/transactions/services/TransactionsService.java
src/test/java/it/pagopa/transactions/services/TransactionServiceTests.java

For more information check this [RFC](https://pagopa.atlassian.net/wiki/spaces/I/pages/703857491/Mapping+stato+transazione+-+pagina+di+esito#Opzione-1)
- Update `getTransactionInfo` with additional information 
- Add `paymentGateway`
- Add `sendPaymentResultOutcome`
- Add `authorizationCode`
- Add `authorizationErrorCode`
- Support pagina esiti landing page
- Unit

[CHK-1543] feat: update getTransactionInfo with additional info

---

src/main/java/it/pagopa/transactions/repositories/TransactionsEventStoreRepository.java
src/main/java/it/pagopa/transactions/utils/TransactionsUtils.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizizationHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionRequestUserReceiptHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionUserCancelHandlerTest.java
src/test/java/it/pagopa/transactions/utils/TransactionsUtilsTest.java

Explicitate orderBy creation date ascending for query used to retrieve events related to a transaction
This modification is needed in order to explicitate creation date ordering when retrieving transaction event
Local test with ecommerce local performing a transaction flow up to the authorization request PATCH checking that transaction events are correctly reduced

fix: reduce orderBy

---

src/main/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandler.java
src/main/java/it/pagopa/transactions/utils/AuthRequestDataUtils.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandlerTest.java
src/test/java/it/pagopa/transactions/utils/AuthRequestDataUtilsTest.java

- truncate to 7 closepayment rrn fox xpay;
The goal of this PR is to accommodate a new requirement from the - xpay node, in particular to truncate to 7 the `rrn` used in the `closepayment request` in the case of authorizations with `xpay`.

feat(rrn): truncate closepayemnt rrn fox xpay

---

.devops/code-review-pipelines.yml
pom.xml
src/main/java/it/pagopa/transactions/client/EcommercePaymentMethodsClient.java
src/main/java/it/pagopa/transactions/services/TransactionsService.java
src/test/java/it/pagopa/transactions/client/EcommercePaymentMethodsClientTest.java
src/test/java/it/pagopa/transactions/services/TransactionServiceTests.java

Depends on https://github.com/pagopa/pagopa-infra/pull/988
Added transactionId header in the calculateFee request performed when authorizing a payment.
The change was made to handle correlation of logs via the transactionId in the payment-methods.
The tests were performed locally.

CHK-1559-added-transactionId-header

---

pom.xml
src/main/java/it/pagopa/transactions/commands/handlers/TransactionActivateHandler.java
src/main/java/it/pagopa/transactions/configurations/RedisConfig.java
src/main/java/it/pagopa/transactions/utils/NodoOperations.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionInitializerHandlerTest.java

Depends on https://github.com/pagopa/pagopa-ecommerce-commons/pull/88
1. Add custom elk span creation during new transaction  processing.
This span is created programmatically only when a transaction is cached for an already activated payment token.
Into custom span are present two labels:
- paymentToken --> valued with transaction payment token
- paymentTokenLeftTimeSec -> numeric label valued with payment token validity left time in seconds 
2. Move PaymentRequestInfo save after Nodo successful payment notice activation 
1. Those modifications are needed in order to track transactions activated close to the Nodo payment token expiration
2. Previously PaymentRequestInfo object were saved for every activation, also for those with a cache hit, causing expiration to be updated for every …

feat: span transaction with left payment token time

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml

Lowered initial delay
After changing application-insight agent with ELK one's deploy times are lower and so initial delay can be lowered accordingly
DEV and UAT deploy.
Actual times:
12:23:43.422 [main] INFO  i.p.t.PagopaEcommerceTransactionsApplication [contextKey= rpt-ids= transaction-id=] - Started PagopaEcommerceTransactionsApplication in 40.568 seconds (JVM running for 49.097)

fix: lowered initial delay

---

pom.xml

feat(common): update common version

---

pom.xml
src/main/java/it/pagopa/transactions/client/NodeForPspClient.java
src/test/java/it/pagopa/transactions/client/NodeForPspClientTest.java

Added into **closePayment** request new query param **_ecomm_**.
The change was made to add a new query param to the close payment request to the node.

feat: added clientId query param  into close payment request

---

.devops/deploy-pipelines.yml
api-spec/transactions-api.yaml
pom.xml
src/main/java/it/pagopa/transactions/client/NodeForPspClient.java
src/main/java/it/pagopa/transactions/commands/handlers/TransactionActivateHandler.java
src/main/java/it/pagopa/transactions/controllers/TransactionsController.java
src/main/java/it/pagopa/transactions/exceptions/PaymentNoticeAllCCPMismatchException.java
src/main/java/it/pagopa/transactions/projections/handlers/AuthorizationUpdateProjectionHandler.java
src/main/java/it/pagopa/transactions/projections/handlers/TransactionsActivationProjectionHandler.java
src/main/java/it/pagopa/transactions/services/TransactionsService.java
src/main/java/it/pagopa/transactions/utils/NodoOperations.java
src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionInitializerHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizizationHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionUpdateAuthorizationHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionsActivationProjectionHandlerTest.java
src/test/java/it/pagopa/transactions/controllers/TransactionsControllerTest.java
src/test/java/it/pagopa/transactions/documents/TransactionDocumentTest.java
src/test/java/it/pagopa/transactions/services/TransactionServiceTest.java
src/test/java/it/pagopa/transactions/services/TransactionServiceTests.java
src/test/java/it/pagopa/transactions/utils/NodoOperationsTest.java

Evaluate allCCP flag and save it into transaction data
Evaluate allCCP flag from nodo activation
Save it to paymentRequest and paymentInfo to save in transaction data
Add the flag to requestAuthorization body after checking value against transaction data
Pass it to payment method when needed
Integrate allCCP flag to GEC API
All junit test have been developed and executed.
Test were performed in local

[CHK-1613] Business logic to evaluate and salve allCCP flag

---

api-spec/transactions-api.yaml

Add sendPaymentResultOutcome NOT_RECEIVED into openapi specifications
Add sendPaymentResultOutcome NOT_RECEIVED into openapi specifications
Junit test + local project build

fix: add NOT_RECEIVED into openapi spec

---

src/main/java/it/pagopa/transactions/configurations/WebClientsConfig.java

Fix payment method api key @Value definition
Fix payment method api key @Value definition
Junit tests

fix: payment method api key conf key

---

Dockerfile
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml

* use OpenTelemetry monitoring agent instead of Elastic APM

[CHK-1590] feat(monitoring): use OpenTelemetry monitoring agent instead of Elastic APM

---

src/main/java/it/pagopa/transactions/utils/EcsEncoderLogMasker.java

Fix: add missing log new line
The missing new line at the end of the single log causes logs to be written on a single line
Local test (main run)

fix: add missing new line in logs

---

pom.xml

Restored main branch for close payment openapi 🙂
The change was made to allow the correct compilation of the main branch of the transaction-service

fix(close payment branch): restore main branch for close payment openapi

---

.devops/deploy-pipelines.yml
.github/actions/check-pr-semver-labels/action.yml
.github/workflows/check_pr.yml
.github/workflows/deploy.yml
README.md

Add github action that check for the presence of well-formed tags that will be used to trigger semantic versioning parameters for deploy module once PR is merge on main branch.
Those tags are:
| Tag                | Semantic versioning scope | Meaning                                                           |
|--------------------|---------------------------|-------------------------------------------------------------------|
| patch              | Application version       | Patch-bump application version into pom.xml and Chart app version |
| minor              | Application version       | Minor-bump application version into pom.xml and Chart app version |
| major              | Application version       | Major-bump application version into pom.xml and Chart app version |
| …

feat(CD): deploy on PR merge

---

.devops/deploy-pipelines.yml

Fix api test on green instance being skipped
Fix api test on green instance being skipped

fix(dedploy-pipeline): api test UAT green

---

.devops/deploy-pipelines.yml

Fix api test condition
Fix api test condition

fix(deploy-pipeline): UAT green api test condition

---

.devops/deploy-pipelines.yml

fix api test task condition
fix api test task condition

fix(deploy-pipeline): UAT api test condition

---

api-spec/transactions-api.yaml
pom.xml
src/test/java/it/pagopa/transactions/controllers/TransactionsControllerTest.java

Depends on https://github.com/pagopa/pagopa-ecommerce-commons/pull/108
Make mail validation case insensitive
Make mail validation case insensitive
Junit tests + local test with ecommerce local

fix(email validation): make email validation case insensitive

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml

Update card logos refs.
Depends on https://github.com/pagopa/pagopa-checkout-fe/pull/234
Update all helm values that points to checkout assets for card logo brands
Align logo images to pagopa standard assets

[CHK-1718] update card logo refs

---

src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestUserReceiptHandler.java
src/main/java/it/pagopa/transactions/configurations/AzureStorageConfig.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionRequestUserReceiptHandlerTest.java

[CHK-1565] feat(tracing): add queue tracing to `TransactionRequestUserReceiptHandler`

---

src/main/java/it/pagopa/transactions/commands/handlers/TransactionUserCancelHandler.java
src/main/java/it/pagopa/transactions/configurations/AzureStorageConfig.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionUserCancelHandlerTest.java

[CHK-1565] feat(tracing): add queue tracing to `TransactionUserCancelHandler`

---

src/main/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandler.java
src/main/java/it/pagopa/transactions/configurations/AzureStorageConfig.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandlerTest.java

[CHK-1565] feat(tracing): add queue client with tracing to `TransactionSendClosureHandler`

---

src/main/java/it/pagopa/transactions/services/TransactionsService.java

Remove circuit breaker from api's that have not external dependency other than Azure resources.
Api's from which circuit breaker configuration has been removed are: 
- user cancel
- authorization status update
- add user receipt
Those api's, in fact, has only Azure as downstream dependency (such as storage queues, cosmos db etc) a no any external service so there is no need for add circuit breaker.
Moreover, the previous configuration cause add user receipt requests to not be processed successfully because of the opened circuit breaker that was wrongly configured as the one used for transaction activation causing avoidable errors returned to the caller (since no downstream dependency was effectively down)

fix(circuit-breaker): remove misconfigured circuit breaker

---

src/main/java/it/pagopa/transactions/utils/NodoOperations.java
src/main/java/it/pagopa/transactions/utils/OpenTelemetryUtils.java
src/test/java/it/pagopa/transactions/utils/NodoOperationsTest.java

Add tracing for Nodo activatePaymentNotice OK operations
This fix is needed in order to trace also OK activatePaymentNotice Nodo operations into Nodo monitoring dashboards
Junit test + test in dev environment
OK ActivatePaymentNotice: 
KO activate payment notice
Dashboard:

fix(monitoring): add tracing for nodo ok activation operations

---

src/main/java/it/pagopa/transactions/configurations/AzureStorageConfig.java

Depends on #265
Depends on #281
Depends on #282
Depends on #283

[CHK-1565] feat(tracing): make traced `QueueAsyncClient` the default

---

helm/values-prod.yaml

* enable OpenTelemetry log sending
Temporary enabling of direct log sending due to missing injection pipeline in prod env

fix: enable OpenTelemetry log sending

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml

Fix helm numeric values as string
This modification is needed in order to avoid `json: cannot unmarshal number into Go struct field ConfigMap.data of type string` error during deploy

fix(helm-values): fixed integer parameters as string

---

api-spec/transactions-api.yaml

Depends on https://github.com/pagopa/pagopa-infra/pull/1256
Add auth request details for handling authorizations performed through NPG
Those modifications are needed in order distinguish auth requests to be performed against NPG service
Local build and code generation

[CHK-1829] feat(auth-request): add auth request details for NPG authorization

---

pom.xml
src/main/java/it/pagopa/transactions/configurations/NpgWebClientsConfig.java
src/test/java/it/pagopa/transactions/client/NpgWebCientConfigTest.java

[CHK-1787] feat(commons): update commons version

---

api-spec/transactions-api.yaml

Depends on https://github.com/pagopa/pagopa-infra/pull/1262
Add update authorization request details to map NPG notification URL information
Those modifications are needed in order to handle payment authorization update request coming from NPG 
Local build

feat(npg): [CHK-1840] add update auth status npg request body choose

---

pom.xml
src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandler.java
src/main/java/it/pagopa/transactions/configurations/NpgWebClientsConfig.java
src/test/java/it/pagopa/transactions/client/NpgWebCientConfigTest.java
src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizizationHandlerTest.java

- add npg client to handle `confirmPayment`;
- update ecommerce common lib to `0.21.0`.
The goal of this PR is to handle npg `confirmPayment` for payment with gdi check and only for happy path.

feat(npg): CHK-1833 add npg confirm payment in auth handler

---

src/main/java/it/pagopa/transactions/configurations/NpgWebClientsConfig.java

fix: api client base path

---

.devops/code-review-pipelines.yml

Depend on https://github.com/pagopa/pagopa-ecommerce-local/pull/90
Added new service to run during `docker-compose up` command into integration tests stage.
Pipeline link: https://dev.azure.com/pagopaspa/pagoPA-projects/_build/results?buildId=115877&view=logs&j=5a5405a0-8439-550a-2a82-0e4c8988d6a1&t=eec4819c-8316-5751-789f-643dbbc4d13d
The change was made to integrate NPG testing into the CR pipeline

feat(CR pipeline) CHK-1882 integration test CR pipeline

---

.devops/code-review-pipelines.yml

Fixed collection folder position into ecommerce local used into CR pipeline

fix(CR pipeline): fixed path collection tests into ecommerce local

---

api-spec/transactions-api.yaml
pom.xml
src/main/java/it/pagopa/transactions/client/EcommercePaymentMethodsClient.java
src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
src/main/java/it/pagopa/transactions/commands/data/AuthorizationRequestData.java
src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandler.java
src/main/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandler.java
src/main/java/it/pagopa/transactions/services/TransactionsService.java
src/main/java/it/pagopa/transactions/utils/AuthRequestDataUtils.java
src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizizationHandlerTest.java
src/test/java/it/pagopa/transactions/services/TransactionServiceTests.java
src/test/java/it/pagopa/transactions/utils/AuthRequestDataUtilsTest.java
src/test/java/it/pagopa/transactions/utils/LogMaskTests.java

Fix NPG logic for handle orderId

---

.env.example
README.md
api-spec/transactions-api.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
pom.xml
src/main/java/it/pagopa/transactions/client/EcommercePaymentMethodsClient.java
src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
src/main/java/it/pagopa/transactions/commands/data/AuthorizationRequestData.java
src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandler.java
src/main/java/it/pagopa/transactions/commands/handlers/TransactionSendClosureHandler.java
src/main/java/it/pagopa/transactions/services/TransactionsService.java
src/main/java/it/pagopa/transactions/utils/AuthRequestDataUtils.java
src/main/resources/application.properties
src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizizationHandlerTest.java
src/test/java/it/pagopa/transactions/services/TransactionServiceTests.java
src/test/java/it/pagopa/transactions/utils/AuthRequestDataUtilsTest.java
src/test/java/it/pagopa/transactions/utils/LogMaskTests.java
src/test/resources/application-tests.properties

fix(deploy): fix NPG url for DEV and UAT envs

---

pom.xml
src/main/java/it/pagopa/transactions/commands/data/AddUserReceiptData.java
src/main/java/it/pagopa/transactions/commands/handlers/TransactionActivateHandler.java
src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestUserReceiptHandlerCommon.java
src/main/java/it/pagopa/transactions/commands/handlers/TransactionUserCancelHandlerCommon.java
src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestUserReceiptHandler.java
src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionSendClosureHandler.java
src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionUserCancelHandler.java
src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestUserReceiptHandler.java
src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionSendClosureHandler.java
src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionUserCancelHandler.java
src/main/java/it/pagopa/transactions/configurations/AzureStorageConfig.java
src/main/java/it/pagopa/transactions/projections/handlers/v1/CancellationRequestProjectionHandler.java
src/main/java/it/pagopa/transactions/projections/handlers/v1/TransactionUserReceiptProjectionHandler.java
src/main/java/it/pagopa/transactions/projections/handlers/v2/CancellationRequestProjectionHandler.java
src/main/java/it/pagopa/transactions/projections/handlers/v2/TransactionUserReceiptProjectionHandler.java
src/main/java/it/pagopa/transactions/services/TransactionsService.java
src/test/java/it/pagopa/transactions/client/NpgWebCientConfigTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionRequestUserReceiptHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/TransactionUserCancelHandlerTest.java
src/test/java/it/pagopa/transactions/projections/handlers/CancellationRequestProjectionHandlerTests.java
src/test/java/it/pagopa/transactions/projections/handlers/TransactionUserReceiptProjectionHandlerTest.java
src/test/java/it/pagopa/transactions/services/TransactionServiceTests.java

Chk 1921 user cancellation handler (#5)

---

helm/values-dev.yaml

Modified WARMUP_REQUEST_NEW_TRANSACTION_NOTICE_CODE_PREFIX env for helm.dev

fix(env): modified WARMUP_REQUEST_NEW_TRANSACTION_NOTICE_CODE_PREFIX for helm dev

---

src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandlerCommon.java
src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java

NPG: set order id as auth-requests `authorizationRequestId` response
This modification fix auth request response body set authorizationRequestId with NPG orderId
Junit tests

fix(npg): return order id into auth requested response

---

helm/values-dev.yaml

Add Nexi and Amex psp as PSP key check parameter for DEV environment
Add Nexi and Amex psp as PSP key check parameter for DEV environment

fix(dev-conf): add nexi and amex for NPG psp key check

---

.devops/code-review-pipelines.yml

Depends on https://github.com/pagopa/pagopa-ecommerce-local/pull/104
Add api tests to cover full transaction (from activation to sendPaymentResult) for:
- NPG
- PGS - XPAY
- PGS - VPOS
Those modifications are needed in order to fully cover transactions-service apis during CR pipeline api test execution
CR pipeline run

feat(CR pipeline): api tests NPG/PGS

---

.devops/deploy-pipelines.yml

Added stages for execute e2e tests after DEV and UAT deploy.
The change was made to perform tests on the FE after the deployment of the service.

feat(deploy pipeline): CHK-1999 e2e tests

---

src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionUpdateAuthorizationHandler.java
src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionUpdateAuthorizationHandler.java

Fix enumeration value
Fix enumeration value

fix: use transaction service status enumeration

---

src/main/java/it/pagopa/transactions/client/NodeForPspClient.java

Add nodo close payment response outcome logging
This log facilitate transaction analysis making Nodo close payment received outcome available into transaction logs

fix: add nodo close payment response outcome logging

---

src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java

Fix update authorization wrong transaction status logging
Fix update authorization wrong transaction status logging
Local test with eCommerce local

fix(logging): fix wrong transaction status log

---

.env.example
README.md
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
pom.xml
src/main/java/it/pagopa/transactions/client/NodeForPspClient.java
src/main/resources/application.properties
src/test/java/it/pagopa/transactions/client/NodeForPspClientTest.java
src/test/resources/application-tests.properties

Parameterize Nodo close payment URI
Parameterize Nodo close payment URI. This modification makes testing nodo communication easier by make close payment and/or activate api calls redirect to mocks in order to simulate error responses, timeout and so on
Local test with eCommerce local + test in dev enviroment (transaction id 0a20b12530834a708bbc1aced26fc81a)

fix: [CHK-2120] - parameterize close payment path

---

helm/values-prod.yaml

feat: disable sendPaymentResult for expired transactions

---

src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionSendClosureHandler.java
src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionSendClosureHandler.java
src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionSendClosureHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionSendClosureHandlerTest.java

Set date time zone to `Europe/Paris` before formatting it to local date time
Set date time zone to `Europe/Paris` before formatting it to local date time
Local tests

fix: [CHK-2221] - close payment additional info timestamp operation

---

src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandlerCommon.java
src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java

Added prefix 'ecommerce-fe' into authorization url during wallet payment flow 
The change was made to manage payment with the wallet

CHK-2249 fix: authorization url for wallet payment 

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java

Modified configuration for outcome and cancel path for wallet payment flow

fix: outcome and cancel path for wallet payment flow

---

helm/values-prod.yaml

Restore update strategy for prod

Restore update strategy for prod

---

pom.xml
src/main/java/it/pagopa/transactions/client/WalletClient.java
src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
src/test/java/it/pagopa/transactions/client/WalletClientTest.java
src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java

Depends on https://github.com/pagopa/pagopa-infra/pull/1603
Depends on https://github.com/pagopa/pagopa-ecommerce-transactions-service/pull/385
Update `wallet auth data` api
The aim of this pr is to update wallet auth data api
Junit tests

Chk 2258 update wallet client

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml

Fix helm values logo map
Fix helm values logo map

fix: helm values

---

helm/values-prod.yaml

feat: enable ff to handle sendpaymentresult for expired transaction

---

helm/values-prod.yaml
helm/values-uat.yaml

Add deployment node with replicas for uat (replicas set to 1) anbd prod (replicas set to 3).
Remove replicas from canary

[CHK-2380] add deployment node for prod

---

api-spec/client/openapi/redirect/redirect-api.yaml
src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java

* switch `idPaymentMethod` and `paymentMethod` in api spec
* change semantics of `paymentMethod` field in Redirect URL retrieval API
* change domain of `idPaymentMethod` field
* add more examples to URL Retrieval API
This PR updates the incoming Checkout Redirect API spec with the latest requirements
Local unit tests
Depends on #403

[CHK-2368] fix(redirect): update redirect API spec

---

api-spec/v1/transactions-api.yaml
src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java
src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTests.java

Api tests CR pipeline fix -> https://github.com/pagopa/pagopa-ecommerce-local/pull/132
Align get transactions response body fields to the one expected in infra specs:
`paymentGateway` -> `gateway`
`authorizationErrorCode` -> `errorCode`
This fix is mandatory in order to fix GET transactions response body to equals the one as exposed on infra specs

fix(spec misalignment): rename misaligned fields

---

api-spec/client/openapi/redirect/redirect-api.yaml
src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandlerCommon.java
src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java

* add `touchpoint` parameter to Redirect PSP API
This PR implements a new requirement to pass the touchpoint that initiated the transaction to the Redirect URL retrieval API
Unit tests
Depends on pagopa/pagopa-ecommerce-local#128

[CHK-2368] feat(redirect): add `touchpoint` parameter to Redirect url retrieval PSP API

---

.devops/code-review-pipelines.yml

Add CR api tests for REDIRECT payment flow
Add CR api tests for REDIRECT payment flow
CR pipeline run -> https://dev.azure.com/pagopaspa/pagoPA-projects/_build/results?buildId=140265&view=logs&s=543f7b97-de0f-5692-d64c-2937e8e5e3be

feat: add CR api tests for redirect payment flow

---

src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionSendClosureHandler.java
src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionSendClosureHandlerTest.java
src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTest.java
src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java

PROD hotfix: invalidate cache after payment gateway authorization have been successfully requested.
In a user payment flow perspective the cache is deleted before the user being redirect to external domain to perform authorization steps
This fix reduce the possibility to have concurrent transactions that will perform a close payment to the Nodo with the same payment token (since payment token in cached).
Removing cache will block subsequent transactions for the same RPT id that will be performed right after the first one obtained the authorization url to init payment phase
Junit tests

fix(cache-invalidation): invalidate cache after auth request

---

helm/values-uat.yaml

Discriminate queues and node client id for UAT blue instance
Discriminate queues and node client id for UAT blue instance

chore(conf): discriminate queues and node close payment for blue instance

---

src/main/java/it/pagopa/transactions/controllers/v2/TransactionsController.java
src/test/java/it/pagopa/transactions/controllers/v2/TransactionsControllerTest.java

Added into Warmup for POST v2/transactions the x-correlation-id.
Added validation for x-correlation-id header

feat: added correlationId exception 400

---

pom.xml
src/main/java/it/pagopa/transactions/commands/data/UpdateAuthorizationStatusData.java
src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
src/test/java/it/pagopa/transactions/commands/data/UpdateAuthorizationStatusDataTest.java
src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionUpdateAuthorizationHandlerTest.java
src/test/java/it/pagopa/transactions/utils/AuthRequestDataUtilsTest.java

* update commons
Depends on pagopa/pagopa-ecommerce-commons/pull/184

[CHK-2575] refactor(redirect): update commons

---

src/main/java/it/pagopa/transactions/commands/data/UpdateAuthorizationStatusData.java

[CHK-2554] fix: spotless

---

src/main/java/it/pagopa/transactions/commands/data/UpdateAuthorizationStatusData.java
src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
src/main/java/it/pagopa/transactions/controllers/v2/TransactionsController.java
src/main/java/it/pagopa/transactions/mdcutilities/TransactionTracingUtils.java
src/test/java/it/pagopa/transactions/controllers/v1/TransactionsControllerTest.java
src/test/java/it/pagopa/transactions/controllers/v2/TransactionsControllerTest.java

-add new field in context log: `apiId`;
The goal of this PR is to add a new field in the log context that clearly indicates which API the log corresponds to. For example for the `post transactions` there is `"apiId":"API-ID-POST-transactions"`:
```json
{
"@timestamp":"2024-03-13T15:13:42.691Z",
"log.level":"INFO",
"message":"Transaction initialized for rptId: *****************************",
"ecs.version":"1.2.0",
"service.name":"pagopa-ecommerce-transactions-service",
"service.version":"1.21.3",
"service.environment":"dev",
"event.dataset":"pagopa-ecommerce-transactions-service",
"process.thread.name":"reactor-http-epoll-2",
"log.logger":"it.pagopa.transactions.services.v1.TransactionsService",
"contextKey":"354f3bb4-efc3-440f-a8c7-8e52db8bc497", …
```

feat: CHK-1938 add an API id in log context

---

src/main/java/it/pagopa/transactions/client/NodeForPspClient.java
src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionActivateHandler.java
src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionActivateHandler.java
src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
src/main/java/it/pagopa/transactions/controllers/v2/TransactionsController.java
src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
src/main/java/it/pagopa/transactions/services/v2/TransactionsService.java
src/main/java/it/pagopa/transactions/utils/NodoOperations.java

The goal of the PR is to enrich the application logs in order to make them more comprehensive, therefore better describing the business logic of the transaction-service APIs.

CHK-1938: log enrichment

---

pom.xml

Fix commons library ref
Fix commons library ref

fix: commons library ref

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml

The goal of this PR is to also add the Redis hostname as a secret, allowing the synchronization of the reference to the new Redis password with any potential hostname updates.

refactor(redis): use new refs for redis

---

src/main/java/it/pagopa/transactions/client/EcommercePaymentMethodsClient.java
src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
src/main/java/it/pagopa/transactions/exceptions/PaymentMethodNotFoundException.java
src/test/java/it/pagopa/transactions/client/EcommercePaymentMethodsClientTest.java
src/test/java/it/pagopa/transactions/controllers/v1/TransactionsControllerTest.java
src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java

* add exception mapping and logging when erroring in `GET /payment-methods/:id`
Without this change, a valid UUID not associated to a payment method would make the service return 500, now it returns 404 with a dedicated exception
**[TODO]**

fix(payment-methods): add exception mapping and logging when erroring in `GET /payment-methods/:id`

---

src/main/resources/application.yml
src/test/java/it/pagopa/transactions/services/v1/CircuitBreakerTest.java

* add missing circuit breaker config for `PaymentMethodNotFoundException`
Fixes a configuration issue on PR #479

fix: add missing circuit breaker config for `PaymentMethodNotFoundException`

---

src/main/java/it/pagopa/transactions/commands/TransactionActivateCommand.java
src/main/java/it/pagopa/transactions/commands/TransactionAddUserReceiptCommand.java
src/main/java/it/pagopa/transactions/commands/TransactionClosureRequestCommand.java
src/main/java/it/pagopa/transactions/commands/TransactionClosureSendCommand.java
src/main/java/it/pagopa/transactions/commands/TransactionRequestAuthorizationCommand.java
src/main/java/it/pagopa/transactions/commands/TransactionUpdateAuthorizationCommand.java
src/main/java/it/pagopa/transactions/commands/TransactionUserCancelCommand.java
src/main/java/it/pagopa/transactions/commands/TransactionsCommand.java
src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionActivateHandler.java
src/main/java/it/pagopa/transactions/commands/handlers/v1/TransactionSendClosureHandler.java
src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionActivateHandler.java
src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
src/main/java/it/pagopa/transactions/controllers/v2/TransactionsController.java
src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
src/main/java/it/pagopa/transactions/services/v2/TransactionsService.java
src/main/java/it/pagopa/transactions/utils/TransactionsUtils.java
src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionActivateHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestAuthorizationHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionRequestUserReceiptHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionSendClosureHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/v1/TransactionUpdateAuthorizationHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionActivateHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestUserReceiptHandlerTest.java
src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionUpdateAuthorizationHandlerTest.java

Fix transaction logging to log all transaction associated RPT ids (for carts transactions)
This modification is needed in order to logs all RPT ids belonging to the current transaction (can be from 1 to 5 in case of cart payments) instead of logging only the first one
Junit tests

fix(logging): handle multiple rpt ids into logs

---

src/main/java/it/pagopa/transactions/configurations/AzureStorageConfig.java
src/main/java/it/pagopa/transactions/configurations/WebClientsConfig.java
src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
src/main/java/it/pagopa/transactions/controllers/v2/TransactionsController.java

1. Configure Netty DNS resolver to use 1 as number of dots in name resolution
2. Add warmup request for GET transaction
3. Perform warmup requests 3 times
1. This modification is a porting of the fix performed [here](https://github.com/pagopa/pagopa-ecommerce-payment-methods-service/pull/191) and applied to all clients
2. GET transaction is one of the most called api since it's called by f.e.'s during transaction outcome polling phase so warmup it before startup can improve performance for newly instantiated pods
3. Testing endpoints empirically without startup the first 2/3 request per endpoint results slower than all the other one. The first is absolutely the slowest one (lazy resource loading and so on) with the second and the third being faster but slightly slower than the others, so …

fix(perf): ndots

---

src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java

Avoid retry on authorization request when gateway returns a 4xx HTTP error code
Avoid retry on authorization request when gateway returns a 4xx HTTP error code
Junit tests

fix: avoid retry on gateway auth request with 4xx response code

---

src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
src/main/java/it/pagopa/transactions/controllers/v2/TransactionsController.java
src/main/java/it/pagopa/transactions/utils/OpenTelemetryUtils.java
src/test/java/it/pagopa/transactions/controllers/v1/TransactionsControllerTest.java
src/test/java/it/pagopa/transactions/controllers/v2/TransactionsControllerTest.java
src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java
src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTests.java

This PR add a opentelemetry span when the circuit breaker is OPEN.
- add span to opened circuit breaker error handler
In many cases, during NPG PROD sessions, elastic reports trace without any span info when the response error is caused by an opened circuit breaker. It's useful to distinguish when an error is caused by circuit breaker or not.
Tested on DEV by mocking NPG 500 responses. Also by simulating a second request coming during circuit breaker open window

fix: add span to tracing circuit breaker

---

api-spec/v1/transactions-api.yaml

Add 422 error response code to auth request api
Add 422 error response code to auth request api

fix(auth-request): add 422 error response code

---

src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java

Add parameter binding for excluded auth request excluded error codes
Without error codes parameter binding set of error codes to be excluded remain empty
Local test with eCommerce local

fix(auth-request): add parameter binding

---

helm/values-prod.yaml

Increase PROD pod memory limit and request to 768 Mib
Increase PROD pod memory limit and request to 768 Mib

chore(chart): increase prod memory limit to 768

---

helm/values-prod.yaml

Add PROD required psp api keys for Redirect payment flow
Add PROD required psp api keys for Redirect payment flow

chore(conf): set redirect psp ids

---

helm/values-prod.yaml

This PR increase min replicas from 3 to 5 pods

chore(helm): increase min replicas to 5

---

helm/values-prod.yaml

fix: Dummy patch for release

---

.devops/code-review-pipelines.yml
README.md
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
src/main/resources/application.properties
src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
src/test/resources/application-tests.properties

Depends on https://github.com/pagopa/pagopa-ecommerce-local/pull/173
Make paymentMethodDescription configurable since it's an optional field into redirect retrieve url request
Add RICO as redirect payment type code
Those modifications are needed in order to handle iConto redirect payment method
Test in DEV environment + junit tests

feat(redirect): parameterize methods descriptions

---

src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java

fix:  wrong clientId outcome url

---

helm/values-prod.yaml

Due to cpu limits increment pod startup time has been reduced to 20 seconds. Initial delay for readiness and liveness can be stepped down to 30 seconds

fix: [CHK-3224] reduce initial delay for liveness and readiness

---

src/main/java/it/pagopa/transactions/controllers/v1/TransactionsController.java
src/main/java/it/pagopa/transactions/controllers/v2/TransactionsController.java
src/main/java/it/pagopa/transactions/mdcutilities/MDCContextLifter.java
src/main/java/it/pagopa/transactions/mdcutilities/MDCFilter.java

- filter reactorContext with only TracingEntry enum
- clear MDC if reactor flow complete
- remove **contextKey** with related copy from mdc to reactor
- remove duplicate newTransaction log
The goal of this PR is to reduce logging size to decrease cost.
**Integration Test logs**
> Before: 
>  [logs_old.txt](https://github.com/user-attachments/files/17329435/logs_old.txt) 823KB
> 
> After:
> [logs_new.txt](https://github.com/user-attachments/files/17329452/logs_new.txt) 162KB 
> 
> **Decrease size of integration test logs: 80%**
**Single log**
> Before: 
> [log-transaction-service-old.json](https://github.com/user-attachments/files/17328479/log-transaction-service-old.json) 4KB
> 
> After:
> [log-transaction-service-new.json](https://github.com/user-attachments/files/17328465/log-transaction …

[CHK-3267] feat: reduce logging size

---

src/main/java/it/pagopa/transactions/mdcutilities/MDCContextLifter.java

Use key instead of enumeration toString value into reactor context map
Use key instead of enumeration toString value into reactor context map
local test with eCommerce local

fix: [CHK-3267] reactor context key

---

helm/values-prod.yaml

Align redirect configuration to prod keys
Add RICO as required key for redirect 
Those modification are required in order to add RICO as required key for prod env

feat: align redirect required keys configuration

---

.devops/code-review-pipelines.yml
api-spec/v2/transactions-api.yaml
pom.xml
src/main/java/it/pagopa/transactions/controllers/v2/TransactionsController.java
src/main/java/it/pagopa/transactions/services/v2/TransactionsService.java
src/test/java/it/pagopa/transactions/controllers/v2/TransactionsControllerTest.java
src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTest.java

Depends on https://github.com/pagopa/pagopa-ecommerce-commons/pull/225
Depends on https://github.com/pagopa/pagopa-ecommerce-local/pull/179
Add GET transaction V2 api call.
This api is an evolution for the v1 version where:
- it have been perform a response body refactoring to aggregate gateway and node information into response body
- add close payment error Node specific information
those modification are needed in order to make:
1. response body clearer
2. return to the caller touchpoint the close payment Node error additional information needed to display error messages to the user based on errors during close payment phase
junit tests + local test with eCommerce local + integrations test in dev env

feat: add get transaction v2

---

pom.xml

update payment wallet infra openapi spec ref
Openapi where taken from deprecated `wallet-app` domain that have been removed, now use `pay-wallet-app` domain
local build

[CHK-3629] fix: wallet api infra ref

---

.devops/azure-templates/maven-github-release.yml

Azure github release deprecated task update:
GitHubRelease@0 -> GitHubRelease@1 
this modification update the task version along with the `tagSource` value that have been changed from the [V0 `manual`](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/github-release-v0?view=azure-pipelines#inputs) to the [V1 `userSpecifiedTag`](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/github-release-v1?view=azure-pipelines#inputs) semantically equivalent value.
Those modifications are needed in order to properly update GitHubRelease deprecated task

chore: update github release task

---

api-spec/v1/transactions-api.yaml
src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java

Add closure error handling
Added the evaluate close payment error data in the outcome evalutation when gateway authorization status is EXECUTED
Add logic business to handle close payment error data

CHK-4107: fix closure error data handling

---

src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java

Handling redirect payment method authorization evaluation
Add business logic to handle authorization status for redirect payments too

[CHK-4108] handle redirect

---

api-spec/v2.1/transactions-api.yaml
src/test/java/it/pagopa/transactions/controllers/v2_1/TransactionsControllerTest.java

- update api spec ref according to https://github.com/pagopa/pagopa-infra/pull/3072
Motivation and Context
The goal of this PR is to update the API specification according to the changes introduced in https://github.com/pagopa/pagopa-infra/pull/3072, to ensure compliance with the VerifyPaymentNotice and ActivationPaymentNotice requirements.
This update is necessary in order to correctly handle payment amounts equal to or greater than 1 million.

fix(ecommerce-amount): PIDM-614 increase max amount spec

---

api-spec/v1/transactions-api.yaml
api-spec/v2/transactions-api.yaml

fix(huge-amount): update v1 and v2 api with huge amount spec

---

pom.xml
src/main/java/it/pagopa/transactions/client/PaymentGatewayClient.java
src/main/java/it/pagopa/transactions/repositories/TransactionCacheInfo.java
src/main/java/it/pagopa/transactions/repositories/WalletPaymentInfo.java
src/test/java/it/pagopa/transactions/PagopaEcommerceTransactionsApplicationTests.java
src/test/java/it/pagopa/transactions/client/PaymentGatewayClientTest.java
src/test/java/it/pagopa/transactions/controllers/v1/TransactionsControllerTest.java
src/test/java/it/pagopa/transactions/controllers/v2/TransactionsControllerTest.java
src/test/java/it/pagopa/transactions/controllers/v2_1/TransactionsControllerTest.java
src/test/java/it/pagopa/transactions/services/v1/CircuitBreakerTest.java
src/test/java/it/pagopa/transactions/services/v1/TransactionServiceTests.java
src/test/java/it/pagopa/transactions/services/v2/CircuitBreakerTest.java
src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTests.java

Take in charge code deprecation replacing deprecated code with suggested one
Take in charge code deprecation replacing deprecated code with suggested one
junit test

fix: code deprecations

---

.devops/code-review-pipelines.yml
pom.xml
src/main/java/it/pagopa/transactions/commands/data/AuthorizationRequestedEventData.java
src/main/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandler.java
src/main/java/it/pagopa/transactions/projections/handlers/v2/AuthorizationRequestProjectionHandler.java
src/main/java/it/pagopa/transactions/projections/handlers/v2/AuthorizationUpdateProjectionHandler.java
src/main/java/it/pagopa/transactions/projections/handlers/v2/CancellationRequestProjectionHandler.java
src/main/java/it/pagopa/transactions/projections/handlers/v2/ClosureRequestedProjectionHandler.java
src/main/java/it/pagopa/transactions/projections/handlers/v2/TransactionUserReceiptProjectionHandler.java
src/main/java/it/pagopa/transactions/projections/handlers/v2/TransactionsActivationProjectionHandler.java
src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
src/test/java/it/pagopa/transactions/projections/handlers/v2/AuthorizationRequestProjectionHandlerTest.java
src/test/java/it/pagopa/transactions/projections/handlers/v2/AuthorizationUpdateProjectionHandlerTest.java
src/test/java/it/pagopa/transactions/projections/handlers/v2/CancellationRequestProjectionHandlerTests.java
src/test/java/it/pagopa/transactions/projections/handlers/v2/ClosureRequestedProjectionHandlerTests.java
src/test/java/it/pagopa/transactions/projections/handlers/v2/TransactionUserReceiptProjectionHandlerTest.java
src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTests.java

- added lastProcessedEventAt from commons library to transactions view for ecommerce-cdc-service usage
This change is needed to keep the view updated with then new field that will be used by ecommerce-cdc-service for event sorting
- Unit tests successful
- Integration tests still working -> https://dev.azure.com/pagopaspa/pagoPA-projects/_build/results?buildId=225383&view=results
- deploy and related api tests/e2e tests still working -> https://dev.azure.com/pagopaspa/pagoPA-projects/_build/results?buildId=225542&view=results
- test after dev deploy (see screenshot for written events in dev db view)
-

feat(cdc-field): [CHK-4349] add lastProcessedEventAt to transactions-view

---

src/main/java/it/pagopa/transactions/commands/handlers/TransactionRequestAuthorizationHandlerCommon.java
src/main/java/it/pagopa/transactions/services/v1/TransactionsService.java
src/test/java/it/pagopa/transactions/commands/handlers/v2/TransactionRequestAuthorizationHandlerTest.java
src/test/java/it/pagopa/transactions/services/v2/TransactionServiceTests.java

Make reactive chain subscribe to reactive operations introduced in this [pr](https://github.com/pagopa/pagopa-ecommerce-transactions-service/pull/677)
Make reactive chain subscribe to reactive operations introduced in this [pr](https://github.com/pagopa/pagopa-ecommerce-transactions-service/pull/677)
Junit tests

fix: subscribe to delete mono

---

.devops/deploy-pipelines.yml

- Migrated DEV and UAT build stages from inline Docker commands to use centralized `azure-pipeline-templates/templates/docker-release/template.yaml`
- Added proper GitHub token file creation for Docker build secrets
- Configured `DOCKER_BUILD_ARGS` parameter to pass GitHub token as Docker secret
The current pipeline implementation uses inline Docker build commands with duplicated logic across multiple services. This approach has several issues:
1. **Code Duplication**: Each service reimplements the same Docker build logic
2. **Maintenance Overhead**: Changes to build process require updates across all services
3. **Inconsistency**: Different services may have slight variations in build commands
This change standardizes all services to use the centralized `azure-pipeline-templates` …

 [CHK-4428] restore template usage and add token file creation
